/**
 * @packageDocumentation
 * @module api.functional.sistema.backups
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IBackup } from "../../../structures/common/IBackup";

/**
 * @controller SistemaController.listarBackups
 * @path GET /sistema/backups
 * @accessor api.functional.sistema.backups.listarBackups
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listarBackups(
  connection: IConnection,
): Promise<listarBackups.Output> {
  return true === connection.simulate
    ? listarBackups.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listarBackups.METADATA,
        template: listarBackups.METADATA.path,
        path: listarBackups.path(),
      });
}
export namespace listarBackups {
  export type Output = Array<IBackup>;

  export const METADATA = {
    method: "GET",
    path: "/sistema/backups",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/sistema/backups";
  export const random = (): Array<IBackup> => typia.random<Array<IBackup>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
