/**
 * @packageDocumentation
 * @module api.functional.ajustes_inventario.items
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IAjusteInventario } from "../../../structures/common/IAjusteInventario";

/**
 * @controller AjusteInventarioController.actualizarItem
 * @path PUT /ajustes-inventario/:id/items/:itemId
 * @accessor api.functional.ajustes_inventario.items.actualizarItem
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function actualizarItem(
  connection: IConnection,
  props: actualizarItem.Props,
): Promise<actualizarItem.Output> {
  return true === connection.simulate
    ? actualizarItem.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...actualizarItem.METADATA,
          template: actualizarItem.METADATA.path,
          path: actualizarItem.path(props),
        },
        props._body,
      );
}
export namespace actualizarItem {
  export type Props = {
    _id: string;
    _itemId: string;
    _body: Body;
  };
  export type Body = IAjusteInventario.IActualizarItem;
  export type Output = IAjusteInventario;

  export const METADATA = {
    method: "PUT",
    path: "/ajustes-inventario/:id/items/:itemId",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/ajustes-inventario/${encodeURIComponent(props._id?.toString() ?? "null")}/items/${encodeURIComponent(props._itemId?.toString() ?? "null")}`;
  export const random = (): IAjusteInventario =>
    typia.random<IAjusteInventario>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.param("_itemId")(() => typia.assert(props._itemId));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
