/**
 * @packageDocumentation
 * @module api.functional.productos.precios
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IPrecioProducto } from "../../../structures/common/IPrecioProducto";

/**
 * @controller ProductoController.listarPrecios
 * @path GET /productos/:id/precios
 * @accessor api.functional.productos.precios.listarPrecios
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listarPrecios(
  connection: IConnection,
  props: listarPrecios.Props,
): Promise<listarPrecios.Output> {
  return true === connection.simulate
    ? listarPrecios.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...listarPrecios.METADATA,
        template: listarPrecios.METADATA.path,
        path: listarPrecios.path(props),
      });
}
export namespace listarPrecios {
  export type Props = {
    _id: string;
  };
  export type Output = Array<IPrecioProducto>;

  export const METADATA = {
    method: "GET",
    path: "/productos/:id/precios",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/productos/${encodeURIComponent(props._id?.toString() ?? "null")}/precios`;
  export const random = (): Array<IPrecioProducto> =>
    typia.random<Array<IPrecioProducto>>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller ProductoController.crearPrecio
 * @path POST /productos/:id/precios
 * @accessor api.functional.productos.precios.crearPrecio
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function crearPrecio(
  connection: IConnection,
  props: crearPrecio.Props,
): Promise<crearPrecio.Output> {
  return true === connection.simulate
    ? crearPrecio.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...crearPrecio.METADATA,
          template: crearPrecio.METADATA.path,
          path: crearPrecio.path(props),
        },
        props._body,
      );
}
export namespace crearPrecio {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IPrecioProducto.ICrear;
  export type Output = IPrecioProducto;

  export const METADATA = {
    method: "POST",
    path: "/productos/:id/precios",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/productos/${encodeURIComponent(props._id?.toString() ?? "null")}/precios`;
  export const random = (): IPrecioProducto => typia.random<IPrecioProducto>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
