/**
 * @packageDocumentation
 * @module api.functional.transferencias
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ITransferenciaAlmacen } from "../../structures/common/ITransferenciaAlmacen";

/**
 * @controller TransferenciaController.listar
 * @path GET /transferencias
 * @accessor api.functional.transferencias.listar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listar(connection: IConnection): Promise<listar.Output> {
  return true === connection.simulate
    ? listar.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listar.METADATA,
        template: listar.METADATA.path,
        path: listar.path(),
      });
}
export namespace listar {
  export type Output = Array<ITransferenciaAlmacen>;

  export const METADATA = {
    method: "GET",
    path: "/transferencias",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/transferencias";
  export const random = (): Array<ITransferenciaAlmacen> =>
    typia.random<Array<ITransferenciaAlmacen>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller TransferenciaController.obtener
 * @path GET /transferencias/:id
 * @accessor api.functional.transferencias.obtener
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function obtener(
  connection: IConnection,
  props: obtener.Props,
): Promise<obtener.Output> {
  return true === connection.simulate
    ? obtener.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...obtener.METADATA,
        template: obtener.METADATA.path,
        path: obtener.path(props),
      });
}
export namespace obtener {
  export type Props = {
    _id: string;
  };
  export type Output = ITransferenciaAlmacen;

  export const METADATA = {
    method: "GET",
    path: "/transferencias/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/transferencias/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): ITransferenciaAlmacen =>
    typia.random<ITransferenciaAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller TransferenciaController.crear
 * @path POST /transferencias
 * @accessor api.functional.transferencias.crear
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function crear(
  connection: IConnection,
  props: crear.Props,
): Promise<crear.Output> {
  return true === connection.simulate
    ? crear.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...crear.METADATA,
          template: crear.METADATA.path,
          path: crear.path(),
        },
        props._body,
      );
}
export namespace crear {
  export type Props = {
    _body: Body;
  };
  export type Body = ITransferenciaAlmacen.ICrear;
  export type Output = ITransferenciaAlmacen;

  export const METADATA = {
    method: "POST",
    path: "/transferencias",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/transferencias";
  export const random = (): ITransferenciaAlmacen =>
    typia.random<ITransferenciaAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller TransferenciaController.actualizar
 * @path PUT /transferencias/:id
 * @accessor api.functional.transferencias.actualizar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function actualizar(
  connection: IConnection,
  props: actualizar.Props,
): Promise<actualizar.Output> {
  return true === connection.simulate
    ? actualizar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...actualizar.METADATA,
          template: actualizar.METADATA.path,
          path: actualizar.path(props),
        },
        props._body,
      );
}
export namespace actualizar {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = ITransferenciaAlmacen.IActualizar;
  export type Output = ITransferenciaAlmacen;

  export const METADATA = {
    method: "PUT",
    path: "/transferencias/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/transferencias/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): ITransferenciaAlmacen =>
    typia.random<ITransferenciaAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
