/**
 * @packageDocumentation
 * @module api.functional.sistema.sincronizar_precios
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ISincronizacionPrecios } from "../../../structures/common/ISincronizacionPrecios";

/**
 * @controller SistemaController.sincronizarPrecios
 * @path POST /sistema/sincronizar-precios
 * @accessor api.functional.sistema.sincronizar_precios.sincronizarPrecios
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function sincronizarPrecios(
  connection: IConnection,
  props: sincronizarPrecios.Props,
): Promise<sincronizarPrecios.Output> {
  return true === connection.simulate
    ? sincronizarPrecios.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...sincronizarPrecios.METADATA,
          template: sincronizarPrecios.METADATA.path,
          path: sincronizarPrecios.path(),
        },
        props._body,
      );
}
export namespace sincronizarPrecios {
  export type Props = {
    _body: Body;
  };
  export type Body = ISincronizacionPrecios.IIniciar;
  export type Output = ISincronizacionPrecios;

  export const METADATA = {
    method: "POST",
    path: "/sistema/sincronizar-precios",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/sistema/sincronizar-precios";
  export const random = (): ISincronizacionPrecios =>
    typia.random<ISincronizacionPrecios>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
