INSERT INTO almacenes (
    id,
    nombre,
    codigo,
    tipo,
    direccion,
    telefono,
    email,
    activo,
    creado_en,
    actualizado_en,
    eliminado_en,
    creado_por,
    actualizado_por
  )
VALUES (
    'id',
    'nombre',
    'codigo',
    'tipo',
    'direccion',
    'telefono',
    'email',
    TRUE,
    'creado_en',
    'actualizado_en',
    'eliminado_en',
    'creado_por',
    'actualizado_por'
  );