/**
 * @packageDocumentation
 * @module api.functional.ventas
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IVenta } from "../../structures/common/IVenta";

/**
 * @controller VentaController.listar
 * @path GET /ventas
 * @accessor api.functional.ventas.listar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listar(connection: IConnection): Promise<listar.Output> {
  return true === connection.simulate
    ? listar.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listar.METADATA,
        template: listar.METADATA.path,
        path: listar.path(),
      });
}
export namespace listar {
  export type Output = Array<IVenta>;

  export const METADATA = {
    method: "GET",
    path: "/ventas",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/ventas";
  export const random = (): Array<IVenta> => typia.random<Array<IVenta>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller VentaController.obtener
 * @path GET /ventas/:id
 * @accessor api.functional.ventas.obtener
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function obtener(
  connection: IConnection,
  props: obtener.Props,
): Promise<obtener.Output> {
  return true === connection.simulate
    ? obtener.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...obtener.METADATA,
        template: obtener.METADATA.path,
        path: obtener.path(props),
      });
}
export namespace obtener {
  export type Props = {
    _id: string;
  };
  export type Output = IVenta;

  export const METADATA = {
    method: "GET",
    path: "/ventas/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/ventas/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IVenta => typia.random<IVenta>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller VentaController.crear
 * @path POST /ventas
 * @accessor api.functional.ventas.crear
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function crear(
  connection: IConnection,
  props: crear.Props,
): Promise<crear.Output> {
  return true === connection.simulate
    ? crear.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...crear.METADATA,
          template: crear.METADATA.path,
          path: crear.path(),
        },
        props._body,
      );
}
export namespace crear {
  export type Props = {
    _body: Body;
  };
  export type Body = IVenta.ICrear;
  export type Output = IVenta;

  export const METADATA = {
    method: "POST",
    path: "/ventas",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/ventas";
  export const random = (): IVenta => typia.random<IVenta>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller VentaController.anular
 * @path PUT /ventas/:id/anular
 * @accessor api.functional.ventas.anular
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function anular(
  connection: IConnection,
  props: anular.Props,
): Promise<anular.Output> {
  return true === connection.simulate
    ? anular.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...anular.METADATA,
          template: anular.METADATA.path,
          path: anular.path(props),
        },
        props._body,
      );
}
export namespace anular {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IVenta.IAnular;
  export type Output = IVenta;

  export const METADATA = {
    method: "PUT",
    path: "/ventas/:id/anular",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/ventas/${encodeURIComponent(props._id?.toString() ?? "null")}/anular`;
  export const random = (): IVenta => typia.random<IVenta>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
