/**
 * @packageDocumentation
 * @module api.functional.ajustes_inventario
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IAjusteInventario } from "../../structures/common/IAjusteInventario";

export * as items from "./items/index";

/**
 * @controller AjusteInventarioController.listar
 * @path GET /ajustes-inventario
 * @accessor api.functional.ajustes_inventario.listar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listar(connection: IConnection): Promise<listar.Output> {
  return true === connection.simulate
    ? listar.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listar.METADATA,
        template: listar.METADATA.path,
        path: listar.path(),
      });
}
export namespace listar {
  export type Output = Array<IAjusteInventario>;

  export const METADATA = {
    method: "GET",
    path: "/ajustes-inventario",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/ajustes-inventario";
  export const random = (): Array<IAjusteInventario> =>
    typia.random<Array<IAjusteInventario>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller AjusteInventarioController.obtener
 * @path GET /ajustes-inventario/:id
 * @accessor api.functional.ajustes_inventario.obtener
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function obtener(
  connection: IConnection,
  props: obtener.Props,
): Promise<obtener.Output> {
  return true === connection.simulate
    ? obtener.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...obtener.METADATA,
        template: obtener.METADATA.path,
        path: obtener.path(props),
      });
}
export namespace obtener {
  export type Props = {
    _id: string;
  };
  export type Output = IAjusteInventario;

  export const METADATA = {
    method: "GET",
    path: "/ajustes-inventario/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/ajustes-inventario/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IAjusteInventario =>
    typia.random<IAjusteInventario>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller AjusteInventarioController.crear
 * @path POST /ajustes-inventario
 * @accessor api.functional.ajustes_inventario.crear
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function crear(
  connection: IConnection,
  props: crear.Props,
): Promise<crear.Output> {
  return true === connection.simulate
    ? crear.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...crear.METADATA,
          template: crear.METADATA.path,
          path: crear.path(),
        },
        props._body,
      );
}
export namespace crear {
  export type Props = {
    _body: Body;
  };
  export type Body = IAjusteInventario.ICrear;
  export type Output = IAjusteInventario;

  export const METADATA = {
    method: "POST",
    path: "/ajustes-inventario",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/ajustes-inventario";
  export const random = (): IAjusteInventario =>
    typia.random<IAjusteInventario>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller AjusteInventarioController.aprobar
 * @path PUT /ajustes-inventario/:id/aprobar
 * @accessor api.functional.ajustes_inventario.aprobar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function aprobar(
  connection: IConnection,
  props: aprobar.Props,
): Promise<aprobar.Output> {
  return true === connection.simulate
    ? aprobar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...aprobar.METADATA,
          template: aprobar.METADATA.path,
          path: aprobar.path(props),
        },
        props._body,
      );
}
export namespace aprobar {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IAjusteInventario.IAprobar;
  export type Output = IAjusteInventario;

  export const METADATA = {
    method: "PUT",
    path: "/ajustes-inventario/:id/aprobar",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/ajustes-inventario/${encodeURIComponent(props._id?.toString() ?? "null")}/aprobar`;
  export const random = (): IAjusteInventario =>
    typia.random<IAjusteInventario>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller AjusteInventarioController.rechazar
 * @path PUT /ajustes-inventario/:id/rechazar
 * @accessor api.functional.ajustes_inventario.rechazar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function rechazar(
  connection: IConnection,
  props: rechazar.Props,
): Promise<rechazar.Output> {
  return true === connection.simulate
    ? rechazar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...rechazar.METADATA,
          template: rechazar.METADATA.path,
          path: rechazar.path(props),
        },
        props._body,
      );
}
export namespace rechazar {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IAjusteInventario.IRechazar;
  export type Output = IAjusteInventario;

  export const METADATA = {
    method: "PUT",
    path: "/ajustes-inventario/:id/rechazar",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/ajustes-inventario/${encodeURIComponent(props._id?.toString() ?? "null")}/rechazar`;
  export const random = (): IAjusteInventario =>
    typia.random<IAjusteInventario>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller AjusteInventarioController.cancelar
 * @path DELETE /ajustes-inventario/:id
 * @accessor api.functional.ajustes_inventario.cancelar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function cancelar(
  connection: IConnection,
  props: cancelar.Props,
): Promise<cancelar.Output> {
  return true === connection.simulate
    ? cancelar.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...cancelar.METADATA,
        template: cancelar.METADATA.path,
        path: cancelar.path(props),
      });
}
export namespace cancelar {
  export type Props = {
    _id: string;
  };
  export type Output = IAjusteInventario;

  export const METADATA = {
    method: "DELETE",
    path: "/ajustes-inventario/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/ajustes-inventario/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IAjusteInventario =>
    typia.random<IAjusteInventario>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}
