/**
 * @packageDocumentation
 * @module api.functional.sistema.restore
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IBackup } from "../../../structures/common/IBackup";

/**
 * @controller SistemaController.restaurar
 * @path POST /sistema/restore/:nombre
 * @accessor api.functional.sistema.restore.restaurar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function restaurar(
  connection: IConnection,
  props: restaurar.Props,
): Promise<void> {
  return true === connection.simulate
    ? restaurar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...restaurar.METADATA,
          template: restaurar.METADATA.path,
          path: restaurar.path(props),
        },
        props._body,
      );
}
export namespace restaurar {
  export type Props = {
    _nombre: string;
    _body: Body;
  };
  export type Body = IBackup.IRestaurar;

  export const METADATA = {
    method: "POST",
    path: "/sistema/restore/:nombre",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/sistema/restore/${encodeURIComponent(props._nombre?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_nombre")(() => typia.assert(props._nombre));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
