/**
 * @packageDocumentation
 * @module api.functional.proveedores
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IProveedor } from "../../structures/common/IProveedor";

/**
 * @controller ProveedorController.listar
 * @path GET /proveedores
 * @accessor api.functional.proveedores.listar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listar(connection: IConnection): Promise<listar.Output> {
  return true === connection.simulate
    ? listar.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listar.METADATA,
        template: listar.METADATA.path,
        path: listar.path(),
      });
}
export namespace listar {
  export type Output = Array<IProveedor>;

  export const METADATA = {
    method: "GET",
    path: "/proveedores",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/proveedores";
  export const random = (): Array<IProveedor> =>
    typia.random<Array<IProveedor>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}

/**
 * @controller ProveedorController.obtener
 * @path GET /proveedores/:id
 * @accessor api.functional.proveedores.obtener
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function obtener(
  connection: IConnection,
  props: obtener.Props,
): Promise<obtener.Output> {
  return true === connection.simulate
    ? obtener.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...obtener.METADATA,
        template: obtener.METADATA.path,
        path: obtener.path(props),
      });
}
export namespace obtener {
  export type Props = {
    _id: string;
  };
  export type Output = IProveedor;

  export const METADATA = {
    method: "GET",
    path: "/proveedores/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/proveedores/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IProveedor => typia.random<IProveedor>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller ProveedorController.crear
 * @path POST /proveedores
 * @accessor api.functional.proveedores.crear
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function crear(
  connection: IConnection,
  props: crear.Props,
): Promise<crear.Output> {
  return true === connection.simulate
    ? crear.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...crear.METADATA,
          template: crear.METADATA.path,
          path: crear.path(),
        },
        props._body,
      );
}
export namespace crear {
  export type Props = {
    _body: Body;
  };
  export type Body = IProveedor.ICrear;
  export type Output = IProveedor;

  export const METADATA = {
    method: "POST",
    path: "/proveedores",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/proveedores";
  export const random = (): IProveedor => typia.random<IProveedor>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller ProveedorController.actualizar
 * @path PUT /proveedores/:id
 * @accessor api.functional.proveedores.actualizar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function actualizar(
  connection: IConnection,
  props: actualizar.Props,
): Promise<actualizar.Output> {
  return true === connection.simulate
    ? actualizar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...actualizar.METADATA,
          template: actualizar.METADATA.path,
          path: actualizar.path(props),
        },
        props._body,
      );
}
export namespace actualizar {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IProveedor.IActualizar;
  export type Output = IProveedor;

  export const METADATA = {
    method: "PUT",
    path: "/proveedores/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/proveedores/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IProveedor => typia.random<IProveedor>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller ProveedorController.eliminar
 * @path DELETE /proveedores/:id
 * @accessor api.functional.proveedores.eliminar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eliminar(
  connection: IConnection,
  props: eliminar.Props,
): Promise<void> {
  return true === connection.simulate
    ? eliminar.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...eliminar.METADATA,
        template: eliminar.METADATA.path,
        path: eliminar.path(props),
      });
}
export namespace eliminar {
  export type Props = {
    _id: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/proveedores/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/proveedores/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}
