/**
 * @packageDocumentation
 * @module api.functional.sistema.logs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { ILogAuditoria } from "../../../structures/common/ILogAuditoria";

/**
 * @controller SistemaController.listarLogs
 * @path GET /sistema/logs
 * @accessor api.functional.sistema.logs.listarLogs
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listarLogs(
  connection: IConnection,
): Promise<listarLogs.Output> {
  return true === connection.simulate
    ? listarLogs.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...listarLogs.METADATA,
        template: listarLogs.METADATA.path,
        path: listarLogs.path(),
      });
}
export namespace listarLogs {
  export type Output = Array<ILogAuditoria>;

  export const METADATA = {
    method: "GET",
    path: "/sistema/logs",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/sistema/logs";
  export const random = (): Array<ILogAuditoria> =>
    typia.random<Array<ILogAuditoria>>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
