/**
 * @packageDocumentation
 * @module api.functional.habilitaciones.almacen
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IHabilitacionAlmacen } from "../../../structures/common/IHabilitacionAlmacen";

/**
 * @controller HabilitacionController.listarPorAlmacen
 * @path GET /habilitaciones/almacen/:almacenId
 * @accessor api.functional.habilitaciones.almacen.listarPorAlmacen
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function listarPorAlmacen(
  connection: IConnection,
  props: listarPorAlmacen.Props,
): Promise<listarPorAlmacen.Output> {
  return true === connection.simulate
    ? listarPorAlmacen.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...listarPorAlmacen.METADATA,
        template: listarPorAlmacen.METADATA.path,
        path: listarPorAlmacen.path(props),
      });
}
export namespace listarPorAlmacen {
  export type Props = {
    _almacenId: string;
  };
  export type Output = Array<IHabilitacionAlmacen>;

  export const METADATA = {
    method: "GET",
    path: "/habilitaciones/almacen/:almacenId",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/habilitaciones/almacen/${encodeURIComponent(props._almacenId?.toString() ?? "null")}`;
  export const random = (): Array<IHabilitacionAlmacen> =>
    typia.random<Array<IHabilitacionAlmacen>>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_almacenId")(() => typia.assert(props._almacenId));
    return random();
  };
}
