/**
 * @packageDocumentation
 * @module api.functional.sistema.backup
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IBackup } from "../../../structures/common/IBackup";

/**
 * @controller SistemaController.generarBackup
 * @path POST /sistema/backup
 * @accessor api.functional.sistema.backup.generarBackup
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function generarBackup(
  connection: IConnection,
): Promise<generarBackup.Output> {
  return true === connection.simulate
    ? generarBackup.simulate(connection)
    : PlainFetcher.fetch(connection, {
        ...generarBackup.METADATA,
        template: generarBackup.METADATA.path,
        path: generarBackup.path(),
      });
}
export namespace generarBackup {
  export type Output = IBackup;

  export const METADATA = {
    method: "POST",
    path: "/sistema/backup",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/sistema/backup";
  export const random = (): IBackup => typia.random<IBackup>();
  export const simulate = (_connection: IConnection): Output => {
    return random();
  };
}
