/**
 * @packageDocumentation
 * @module api.functional.habilitaciones
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IHabilitacionAlmacen } from "../../structures/common/IHabilitacionAlmacen";

export * as almacen from "./almacen/index";

/**
 * @controller HabilitacionController.obtener
 * @path GET /habilitaciones/:id
 * @accessor api.functional.habilitaciones.obtener
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function obtener(
  connection: IConnection,
  props: obtener.Props,
): Promise<obtener.Output> {
  return true === connection.simulate
    ? obtener.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...obtener.METADATA,
        template: obtener.METADATA.path,
        path: obtener.path(props),
      });
}
export namespace obtener {
  export type Props = {
    _id: string;
  };
  export type Output = IHabilitacionAlmacen;

  export const METADATA = {
    method: "GET",
    path: "/habilitaciones/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/habilitaciones/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IHabilitacionAlmacen =>
    typia.random<IHabilitacionAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller HabilitacionController.crear
 * @path POST /habilitaciones
 * @accessor api.functional.habilitaciones.crear
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function crear(
  connection: IConnection,
  props: crear.Props,
): Promise<crear.Output> {
  return true === connection.simulate
    ? crear.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...crear.METADATA,
          template: crear.METADATA.path,
          path: crear.path(),
        },
        props._body,
      );
}
export namespace crear {
  export type Props = {
    _body: Body;
  };
  export type Body = IHabilitacionAlmacen.ICrear;
  export type Output = IHabilitacionAlmacen;

  export const METADATA = {
    method: "POST",
    path: "/habilitaciones",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/habilitaciones";
  export const random = (): IHabilitacionAlmacen =>
    typia.random<IHabilitacionAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(),
      contentType: "application/json",
    });
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller HabilitacionController.actualizar
 * @path PUT /habilitaciones/:id
 * @accessor api.functional.habilitaciones.actualizar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function actualizar(
  connection: IConnection,
  props: actualizar.Props,
): Promise<actualizar.Output> {
  return true === connection.simulate
    ? actualizar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...actualizar.METADATA,
          template: actualizar.METADATA.path,
          path: actualizar.path(props),
        },
        props._body,
      );
}
export namespace actualizar {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IHabilitacionAlmacen.IActualizar;
  export type Output = IHabilitacionAlmacen;

  export const METADATA = {
    method: "PUT",
    path: "/habilitaciones/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/habilitaciones/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IHabilitacionAlmacen =>
    typia.random<IHabilitacionAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}

/**
 * @controller HabilitacionController.eliminar
 * @path DELETE /habilitaciones/:id
 * @accessor api.functional.habilitaciones.eliminar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function eliminar(
  connection: IConnection,
  props: eliminar.Props,
): Promise<void> {
  return true === connection.simulate
    ? eliminar.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...eliminar.METADATA,
        template: eliminar.METADATA.path,
        path: eliminar.path(props),
      });
}
export namespace eliminar {
  export type Props = {
    _id: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/habilitaciones/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/habilitaciones/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): void => typia.random<void>();
  export const simulate = (connection: IConnection, props: Props): void => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}
