/**
 * @packageDocumentation
 * @module api.functional.stocks
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { NestiaSimulator } from "@nestia/fetcher/lib/NestiaSimulator";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";
import typia from "typia";

import type { IStockAlmacen } from "../../structures/common/IStockAlmacen";

export * as almacen from "./almacen/index";

/**
 * @controller StockController.obtener
 * @path GET /stocks/:id
 * @accessor api.functional.stocks.obtener
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function obtener(
  connection: IConnection,
  props: obtener.Props,
): Promise<obtener.Output> {
  return true === connection.simulate
    ? obtener.simulate(connection, props)
    : PlainFetcher.fetch(connection, {
        ...obtener.METADATA,
        template: obtener.METADATA.path,
        path: obtener.path(props),
      });
}
export namespace obtener {
  export type Props = {
    _id: string;
  };
  export type Output = IStockAlmacen;

  export const METADATA = {
    method: "GET",
    path: "/stocks/:id",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Props) =>
    `/stocks/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IStockAlmacen => typia.random<IStockAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    return random();
  };
}

/**
 * @controller StockController.actualizar
 * @path PUT /stocks/:id
 * @accessor api.functional.stocks.actualizar
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function actualizar(
  connection: IConnection,
  props: actualizar.Props,
): Promise<actualizar.Output> {
  return true === connection.simulate
    ? actualizar.simulate(connection, props)
    : PlainFetcher.fetch(
        {
          ...connection,
          headers: {
            ...connection.headers,
            "Content-Type": "application/json",
          },
        },
        {
          ...actualizar.METADATA,
          template: actualizar.METADATA.path,
          path: actualizar.path(props),
        },
        props._body,
      );
}
export namespace actualizar {
  export type Props = {
    _id: string;
    _body: Body;
  };
  export type Body = IStockAlmacen.IActualizar;
  export type Output = IStockAlmacen;

  export const METADATA = {
    method: "PUT",
    path: "/stocks/:id",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (props: Omit<Props, "_body">) =>
    `/stocks/${encodeURIComponent(props._id?.toString() ?? "null")}`;
  export const random = (): IStockAlmacen => typia.random<IStockAlmacen>();
  export const simulate = (connection: IConnection, props: Props): Output => {
    const assert = NestiaSimulator.assert({
      method: METADATA.method,
      host: connection.host,
      path: path(props),
      contentType: "application/json",
    });
    assert.param("_id")(() => typia.assert(props._id));
    assert.body(() => typia.assert(props._body));
    return random();
  };
}
