name: build
on:
  pull_request:
    paths:
      - 'prisma/**'
      - 'src/**'
      - 'test/**'
      - 'package.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    env:
      DB_PROVIDER: mysql
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: ipsx4w
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping --silent" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      
      - name: Install Backend-Server
        run: pnpm install

      - name: Compile Backend-Server
        run: npm run build
      
      - name: Create DB Schema
        env:
          DB_PROVIDER: mysql
        run: npm run schema root

      - name: Test Backend-Server
        env:
          DB_PROVIDER: mysql
        run: npm run test -- --reset true --simultaneous 16
